(Fix CI) Remove Ruby 3.0 since it's EOL
Bundle install is getting this error trying to build sqlite:

```
/opt/hostedtoolcache/Ruby/3.0.7/x64/lib/ruby/3.0.0/psych.rb:457:in
`parse_stream': undefined method `parse' for #<Psych::Parser:0x0000556fbb470240
@handler=#<Psych::Handlers::DocumentStream:0x0000556fbb470358 @stack=[],
@last=nil, @root=nil, @start_line=nil, @start_column=nil, @end_line=nil,
@end_column=nil, @block=#<Proc:0x0000556fbb470290
/opt/hostedtoolcache/Ruby/3.0.7/x64/lib/ruby/3.0.0/psych.rb:391>>,
@external_encoding=0> (NoMethodError)
	from /opt/hostedtoolcache/Ruby/3.0.7/x64/lib/ruby/3.0.0/psych.rb:391:in `parse'
from /opt/hostedtoolcache/Ruby/3.0.7/x64/lib/ruby/3.0.0/psych.rb:280:in
`unsafe_load'
from /opt/hostedtoolcache/Ruby/3.0.7/x64/lib/ruby/3.0.0/psych.rb:583:in `block
in unsafe_load_file'
	from /opt/hostedtoolcache/Ruby/3.0.7/x64/lib/ruby/3.0.0/psych.rb:582:in `open'
from /opt/hostedtoolcache/Ruby/3.0.7/x64/lib/ruby/3.0.0/psych.rb:582:in
`unsafe_load_file'
	from extconf.rb:161:in `mini_portile_config'
	from extconf.rb:157:in `sqlite3_config'
	from extconf.rb:141:in `minimal_recipe'
	from extconf.rb:51:in `configure_packaged_libraries'
	from extconf.rb:17:in `configure'
	from extconf.rb:284:in `<main>'

extconf failed, exit code 1
```

It sounds like updating system bundler will fix it, but 3.0 is EOL now
anyway, so it seems simpler to just remove it.